version: '3.1'

services:
  my-registry:
    image: registry:2.6.1
    volumes:
      - registry:/var/lib/registry
    ports:
      - "55000:5000"
    restart: unless-stopped
    environment:
            REGISTRY_STORAGE_DELETE_ENABLED : "True"

volumes:
  registry:

